export const FETCH_STUDENTS_DETAILS_REQUEST = "FETCH_STUDENTS_DETAILS_REQUEST"; 
export const FETCH_STUDENTS_DETAILS_SUCCESS = "FETCH_STUDENTS_DETAILS_SUCCESS"; 
export const FETCH_STUDENTS_DETAILS_FAILURE = "FETCH_STUDENTS_DETAILS_FAILURE"; 

export const SEND_PROGRESS_EMAILS_REQUEST = "SEND_PROGRESS_EMAILS_REQUEST"; 
export const SEND_PROGRESS_EMAILS_SUCCESS = "SEND_PROGRESS_EMAILS_SUCCESS"; 
export const SEND_PROGRESS_EMAILS_FAILURE = "SEND_PROGRESS_EMAILS_FAILURE"; 